name: backtest-and-report
on:
  push:
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run backtest
        run: |
          python backtest.py  # CSV/PNG/metricsを出力する想定
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backtest-outputs
          path: |
            reports/*
            outputs/*
      - name: Post summary
        run: |
          echo "## 今回のバックテスト結果" >> $GITHUB_STEP_SUMMARY
          echo "- 年率: $(cat reports/annual_return.txt)" >> $GITHUB_STEP_SUMMARY
          echo "- シャープ: $(cat reports/sharpe.txt)" >> $GITHUB_STEP_SUMMARY
          echo '![equity](reports/equity_curve.png)' >> $GITHUB_STEP_SUMMARY
