name: backtest-and-report

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install yfinance matplotlib pandas scikit-learn boxsdk

      - name: Run backtest
        run: python main.py

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Define upload helper
        run: |
          echo '#!/bin/bash' > upload_or_update.sh
          echo 'FILE_PATH="$1"' >> upload_or_update.sh
          echo 'FOLDER_ID="347316441372"' >> upload_or_update.sh
          echo 'FILE_NAME=$(basename "$FILE_PATH")' >> upload_or_update.sh
          echo 'ACCESS_TOKEN="${{ secrets.BOX_ACCESS_TOKEN }}"' >> upload_or_update.sh
          echo 'FILE_ID=$(curl -s -X GET "https://api.box.com/2.0/folders/$FOLDER_ID/items?fields=name" -H "Authorization: Bearer $ACCESS_TOKEN" | jq -r --arg NAME "$FILE_NAME" ''.entries[] | select(.name==$NAME) | .id'')' >> upload_or_update.sh
          echo 'if [ -n "$FILE_ID" ]; then' >> upload_or_update.sh
          echo '  curl -s -X POST "https://upload.box.com/api/2.0/files/$FILE_ID/content" -H "Authorization: Bearer $ACCESS_TOKEN" -F "file=@$FILE_PATH"' >> upload_or_update.sh
          echo 'else' >> upload_or_update.sh
          echo '  curl -s -X POST "https://upload.box.com/api/2.0/files/content" -H "Authorization: Bearer $ACCESS_TOKEN" -F "attributes={\"name\":\"$FILE_NAME\",\"parent\":{\"id\":\"$FOLDER_ID\"}}" -F "file=@$FILE_PATH"' >> upload_or_update.sh
          echo 'fi' >> upload_or_update.sh
          chmod +x upload_or_update.sh

      - name: Upload reports to Box
        run: |
          ./upload_or_update.sh reports/pred_vs_actual.png
          ./upload_or_update.sh reports/equity_curve.png
          ./upload_or_update.sh reports/metrics.txt