name: backtest-and-report
on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BOX_TOKEN: ${{ secrets.BOX_DEVELOPER_TOKEN }}
      BOX_FOLDER_ID: ${{ secrets.BOX_FOLDER_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run backtest
        run: |
          python main.py  # reports/ に3ファイル出力: PNG2枚とmetrics.txt

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Define helper (upload_or_update.sh)
        shell: bash
        run: |
          cat << 'EOS' > upload_or_update.sh
          #!/usr/bin/env bash
          set -euo pipefail
          FILEPATH="$1"
          BASENAME="$(basename "$FILEPATH")"

          # 1) フォルダ内ファイル一覧を取得
          ITEMS_JSON="$(curl -sS "https://api.box.com/2.0/folders/${BOX_FOLDER_ID}/items?fields=id,name&limit=1000" \
            -H "Authorization: Bearer ${BOX_TOKEN}")"

          # 2) 同名ファイルIDを抽出
          FILE_ID="$(echo "$ITEMS_JSON" | jq -r --arg NAME "$BASENAME" '.entries[] | select(.name == $NAME) | .id' | head -n1 || true)"

          if [[ -n "${FILE_ID}" && "${FILE_ID}" != "null" ]]; then
            echo "Updating existing file ${BASENAME} (id=${FILE_ID})"
            curl -sS -X POST "https://upload.box.com/api/2.0/files/${FILE_ID}/content" \
              -H "Authorization: Bearer ${BOX_TOKEN}" \
              -F "file=@${FILEPATH}" > /dev/null
          else
            echo "Uploading new file ${BASENAME} to folder ${BOX_FOLDER_ID}"
            curl -sS "https://upload.box.com/api/2.0/files/content" \
              -H "Authorization: Bearer ${BOX_TOKEN}" \
              -F "attributes={\"name\":\"${BASENAME}\",\"parent\":{\"id\":\"${BOX_FOLDER_ID}\"}}" \
              -F "file=@${FILEPATH}" > /dev/null
          fi
          echo "✅ Done: ${BASENAME}"
          EOS
          chmod +x upload_or_update.sh

      - name: Upload reports to Box (overwrite-if-exists)
  run: |
    ./upload_or_update.sh reports/price_with_trades.png
    ./upload_or_update.sh reports/equity_curve.png
    ./upload_or_update.sh reports/trades.csv
    ./upload_or_update.sh reports/metrics.txt